spring.application.name=printpilot-api

# Datasource configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/printpilot}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:printpilot}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
